"""create pricing and depara tables

Revision ID: 46cd26820526
Revises: 
Create Date: 2026-04-29 15:34:42.191070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cd26820526'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depara_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('source_value', sa.String(length=200), nullable=False),
    sa.Column('target_value', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mapping_type', 'source_value', 'target_value', name='uq_depara')
    )
    op.create_table('pricing_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente', sa.String(length=180), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('datasul_code', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('subcategory', sa.String(length=120), nullable=False),
    sa.Column('size', sa.String(length=60), nullable=True),
    sa.Column('manager', sa.String(length=120), nullable=True),
    sa.Column('channel', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('previous_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('margin', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('updated_at_source', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_history')
    op.drop_table('depara_mappings')
    # ### end Alembic commands ###
