"""
Seed — pricing_history
Fonte oficial: BD - Histórico de preços.xlsx
19 registros representativos para homologação.
 
Cobertura:
  - 8 clientes: CIMED, DECATHLON, GLEMOSA, HACK, HIVE, MASTERWAY, VITAMEDIC, Z2
  - 5 categorias: Cápsula, Gel, Outros, Pastilha, Pó
  - múltiplos meses para testar filtros e analytics
 
Executar via: python -m app.seeds.run_seeds
"""
 
from __future__ import annotations
 
from app.infrastructure.supabase_client import supabase
 
TABLE = "pricing_history"
 
PRICING_SEED_DATA = [
    {
        "cliente": "GLEMOSA",
        "sku": "GLEMOSA - COLÁGENO VERISOL FRUTAS VERMELHAS - POTE 300G",
        "datasul_code": "4004.0014.0171",
        "category": "Pó",
        "subcategory": "Colágeno",
        "size": "3",
        "manager": "Stephanie",
        "status": "Ativo",
        "current_price": 3.32,
        "previous_price": 3.32,
        "cost": None,
        "margin": 47.33,
        "currency": "BRL",
        "month": "2027-12",
    },
    {
        "cliente": "HACK",
        "sku": "HACK - GEL ROXAS CAF+TAU- DISPLAY C/10 400G",
        "datasul_code": "4030.0014.0175",
        "category": "Gel",
        "subcategory": None,
        "size": "3",
        "manager": "Stephanie",
        "status": "Ativo",
        "current_price": 32.86,
        "previous_price": 38.88,
        "cost": None,
        "margin": 38.55,
        "currency": "BRL",
        "month": "2025-09",
    },
    {
        "cliente": "MASTERWAY",
        "sku": "GEL CAF + TAU FRUTAS VERMELHAS (40G) DISPLAY COM 10",
        "datasul_code": "4030.0014.0191",
        "category": "Gel",
        "subcategory": None,
        "size": "2",
        "manager": "Leticia",
        "status": "Ativo",
        "current_price": 30.4,
        "previous_price": 38.07,
        "cost": None,
        "margin": 29.14,
        "currency": "BRL",
        "month": "2026-11",
    },
    {
        "cliente": "VITAMEDIC",
        "sku": "VITAMEDIC - WARM UP (006052) - POTE 110G",
        "datasul_code": "4030.0002.0062",
        "category": "Outros",
        "subcategory": None,
        "size": "3",
        "manager": "Eduardo",
        "status": "Ativo",
        "current_price": 12.95,
        "previous_price": 17.38,
        "cost": None,
        "margin": 35.72,
        "currency": "BRL",
        "month": "2025-01",
    },
    {
        "cliente": "VITAMEDIC",
        "sku": "WARM UP PO 110G   ( 006052 )",
        "datasul_code": "4030.0002.0062",
        "category": "Outros",
        "subcategory": None,
        "size": "3",
        "manager": "Eduardo",
        "status": "Ativo",
        "current_price": 2.1,
        "previous_price": 2.82,
        "cost": None,
        "margin": 49.25,
        "currency": "BRL",
        "month": "2023-10",
    },
    {
        "cliente": "VITAMEDIC",
        "sku": "WARM UP PO 110G   ( 006052 )",
        "datasul_code": "4030.0002.0062",
        "category": "Outros",
        "subcategory": None,
        "size": "3",
        "manager": "Eduardo",
        "status": "Ativo",
        "current_price": 28.82,
        "previous_price": 38.67,
        "cost": None,
        "margin": 37.85,
        "currency": "BRL",
        "month": "2022-10",
    },
    {
        "cliente": "DECATHLON",
        "sku": "ULTRA FRUTAS VERMELHAS (40G) DISPLAY COM 10",
        "datasul_code": "4030.0014.0028",
        "category": "Gel",
        "subcategory": None,
        "size": "1",
        "manager": "Eduardo",
        "status": "Ativo",
        "current_price": 3.95,
        "previous_price": 3.95,
        "cost": None,
        "margin": 42.36,
        "currency": "BRL",
        "month": "2026-02",
    },
    {
        "cliente": "DECATHLON",
        "sku": "ENERGY CARAMELO SALTED (40G) DISPLAY COM 10",
        "datasul_code": "4030.0014.0029",
        "category": "Gel",
        "subcategory": None,
        "size": "1",
        "manager": "Eduardo",
        "status": "Ativo",
        "current_price": 31.55,
        "previous_price": 33.93,
        "cost": None,
        "margin": 44.52,
        "currency": "BRL",
        "month": "2025-07",
    },
    {
        "cliente": "DECATHLON",
        "sku": "ENERGY LIMÃO (40G) DISPLAY COM 10",
        "datasul_code": "4030.0014.0024",
        "category": "Gel",
        "subcategory": None,
        "size": "1",
        "manager": "Eduardo",
        "status": "Ativo",
        "current_price": 3.95,
        "previous_price": 3.95,
        "cost": None,
        "margin": 41.22,
        "currency": "BRL",
        "month": "2025-06",
    },
    {
        "cliente": "DECATHLON",
        "sku": "PRO CHOCOLATE (40G) DISPLAY COM 10",
        "datasul_code": "4030.0014.0076",
        "category": "Gel",
        "subcategory": None,
        "size": "1",
        "manager": "Eduardo",
        "status": "Ativo",
        "current_price": 43.8,
        "previous_price": 58.78,
        "cost": None,
        "margin": 32.57,
        "currency": "BRL",
        "month": "2025-05",
    },
    {
        "cliente": "CIMED",
        "sku": "CIMED - LAVITAN COLÁGENO VERISOL HIBISCO E LIMÃO - POTE 300G",
        "datasul_code": "4045.0002.0024",
        "category": "Pó",
        "subcategory": "Colágeno",
        "size": "1",
        "manager": "Leticia",
        "status": "Ativo",
        "current_price": 23.93,
        "previous_price": 28.36,
        "cost": None,
        "margin": 13.46,
        "currency": "BRL",
        "month": "2025-12",
    },
    {
        "cliente": "CIMED",
        "sku": "CIMED - LAVITAN MAÇA VERDE IFP0041.T006 - POTE 300G",
        "datasul_code": "4004.0014.0082",
        "category": "Pó",
        "subcategory": "Colágeno",
        "size": "1",
        "manager": "Leticia",
        "status": "Ativo",
        "current_price": 13.87,
        "previous_price": 16.41,
        "cost": None,
        "margin": 17.45,
        "currency": "BRL",
        "month": "2025-01",
    },
    {
        "cliente": "CIMED",
        "sku": "CIMED - LAVITAN COLÁGENO VERISOL HIBISCO E LIMÃO - POTE 300G",
        "datasul_code": "4045.0002.0024",
        "category": "Pó",
        "subcategory": "Colágeno",
        "size": "1",
        "manager": "Leticia",
        "status": "Ativo",
        "current_price": 18.36,
        "previous_price": 19.53,
        "cost": None,
        "margin": 48.34,
        "currency": "BRL",
        "month": "2023-12",
    },
    {
        "cliente": "CIMED",
        "sku": "CIMED - LAVITAN COLÁGENO VERISOL HIBISCO E LIMÃO - POTE 300G",
        "datasul_code": "4045.0002.0024",
        "category": "Pó",
        "subcategory": "Colágeno",
        "size": "1",
        "manager": "Leticia",
        "status": "Ativo",
        "current_price": 17.78,
        "previous_price": 21.04,
        "cost": None,
        "margin": 45.7,
        "currency": "BRL",
        "month": "2023-10",
    },
    {
        "cliente": "HIVE",
        "sku": "HIVE - SPARK 525G",
        "datasul_code": "4004.0014.0070",
        "category": "Outros",
        "subcategory": None,
        "size": "2",
        "manager": "Leticia",
        "status": "Ativo",
        "current_price": 9.96,
        "previous_price": 9.96,
        "cost": None,
        "margin": 48.22,
        "currency": "BRL",
        "month": "2026-02",
    },
    {
        "cliente": "HIVE",
        "sku": "HIVE - COLAGENO CAPSULA TIPO LL - 60UN",
        "datasul_code": "4004.0014.0076",
        "category": "Cápsula",
        "subcategory": None,
        "size": "2",
        "manager": "Leticia",
        "status": "Ativo",
        "current_price": 6.92,
        "previous_price": 6.92,
        "cost": None,
        "margin": 51.84,
        "currency": "BRL",
        "month": "2026-01",
    },
    {
        "cliente": "HIVE",
        "sku": "HIVE - HYPER CREAM PROT CHOCOLATE - POUCH 450G IFP0117.T017",
        "datasul_code": "4004.0014.0159",
        "category": "Pó",
        "subcategory": "Proteína",
        "size": "2",
        "manager": "Leticia",
        "status": "Ativo",
        "current_price": 29.87,
        "previous_price": 35.34,
        "cost": None,
        "margin": 39.97,
        "currency": "BRL",
        "month": "2025-11",
    },
    {
        "cliente": "HIVE",
        "sku": "HIVE - RESKIN TANGERINA 300G",
        "datasul_code": "4004.0014.0064",
        "category": "Outros",
        "subcategory": None,
        "size": "2",
        "manager": "Leticia",
        "status": "Ativo",
        "current_price": 34.15,
        "previous_price": 42.77,
        "cost": None,
        "margin": 29.93,
        "currency": "BRL",
        "month": "2025-10",
    },
    {
        "cliente": "Z2",
        "sku": "PASTILHA SALTZ LIMÃO  - DISPLAY C/ 10 - 130G",
        "datasul_code": "4030.0014.0105",
        "category": "Pastilha",
        "subcategory": None,
        "size": "2",
        "manager": "Eduardo",
        "status": "Ativo",
        "current_price": 27.49,
        "previous_price": 34.43,
        "cost": None,
        "margin": 48.73,
        "currency": "BRL",
        "month": "2026-04",
    },
]
 
 
def run() -> None:
    print("Iniciando seed de pricing_history...")
 
    inseridos = 0
    erros = 0
 
    for item in PRICING_SEED_DATA:
        try:
            supabase.table(TABLE).insert(item).execute()
            print(f'  ✅ Inserido: {item["cliente"]} | {item["sku"][:45]} | {item["month"]}')
            inseridos += 1
        except Exception as e:
            print(f'  ❌ Erro: {item["cliente"]} | {e}')
            erros += 1
 
    print(f"\n  pricing_history: {inseridos} inseridos, {erros} erros.")